l_simp_chinese:
 DIVISION_QUEUED:0 "$N$ 支部隊"
 DIVISIONS_QUEUED:0 "$N$ 支部隊"
 CONVEYOR_EQUIPMENT_NEED:0 "裝備需求："
 CONVEYOR_MANPOWER_NEED:0 "人力需求：$AMOUNT|H$"
 DEPLOYMENT_REQUIREMENT:0 "$NAME$：$AMOUNT$"
 DEPLOYMENT_DIVISION_LABEL:0 "單位"
 DEPLOYMENT_PROGRESS_LABEL:0 "進度"
 DEPLOYMENT_PRIORITY_LABEL:0 "優先級"
 DEPLOYMENT_DEPLOY_LABEL:0 "部署"
 DEPLOYMENT_TEMPLATE_ITEM_ADD:0 "§G點擊左鍵，即可加入部署序列§!"
 DEPLOYMENT_TEMPLATE_ITEM_COPY:0 "§G點擊左鍵§!，即可複製。"
 DEPLOYMENT_TEMPLATE_ITEM_EDIT:0 "§G點擊左鍵§!，即可編輯。"
 DEPLOYMENT_TEMPLATE_ITEM_VIEW:0 "§G點擊以檢視部隊編制§!"
 DEPLOYMENT_TRAINING:0 "訓練進度：$VALUE|%Y0$/$MAXVALUE|$"
 DEPLOYMENT_TRAINING_MAXVALUE_DESC:0 "$VALUE|H%0$（單位的經驗等級取決於裝備是否齊全）"
 DEPLOYMENT_CURRENT_LEVEL:0 "目前的經驗等級為 §G$NUMBER$§! 等（$LEVEL|%Y0$）"
 DEPLOYMENT_MANPOWER_DESC:0 "兵員：$VALUE|Y0$/$MAX|Y0$"
 DEPLOYMENT_EXPERIENCE_DESC:0 "\n該部隊在結訓後的經驗等級為 §G$NUMBER$§! 等（$MAXLEVEL|%Y0$），並且獲得$EFFECT|+=%0$的戰鬥修正。"
 DEPLOYMENT_EXPERIENCE_ESTIMATED_DESC:0 "\n只要所需裝備齊全，即可在 §Y$DATE$年結訓。"
 DEPLOYMENT_EQUIPMENT:0 "編裝比：$VALUE|%Y0$"
 DEPLOYMENT_EQUIPMENT_FULL_DESC:0 "$NAME$：$VALUE|G0$/$MAX|G0$"
 DEPLOYMENT_EQUIPMENT_DESC:0 "$NAME$：$VALUE|Y0$/$MAX|Y0$"
 DEPLOYMENT_DESIGNER:0 "管理編制"
 DEPLOYMENT_EQUIPMENT_VARIANT_AMOUNT:0 "$NAME|Y$：$VALUE|Y0$"
 DEPLOYMENT_EQUIPMENT_VARIANT_AMOUNT_FULL:0 "$NAME|G$：$VALUE|G0$"
 DEPLOYMENT_EQUIPMENT_CHANGE:0 "$NAME$：$VALUE$"
 DEPLOYMENT_ADD_TEMPLATE:0 "訓練"
 DEPLOYMENT_LINES_HIT_THE_CAP:0 "目前訓練人數上限：$CAP|*H$\n這是由現役人口所決定的（$INFIELD|*H$中的$RATIO|H0%$。下限：$MINPOSSIBLE|*H$）"
 REGIMENTS_SELECTION_CANCEL:0 "返回"
 ONLY_ONE_TEMPLATE_LEFT:0 "無法删除唯一的編制。"
 DELETE_TEMPLATE:0 "從列表中§R删除§!編制。"
 DELETE_TEMPLATE_TITLE:0 "删除編制"
 DELETE_TEMPLATE_DESC:0 "您確定要删除這個編制嗎？"
 DEPLOYMENT_REMOVE_DIVISION:0 "取消單位"
 DEPLOYMENT_DEPLOYMENT_LABEL:0 "兵役署"
 DEPLOYMENT_NOT_ALLOWED_REASON_EQUIPMENT:0 "無法§R部署§!沒有裝備的部隊。\n請等待裝備到達後再進行部署。"
 DEPLOYMENT_NOT_ALLOWED_REASON_MANPOWER:0 "無法§R部署§!沒有兵員的部隊。"
 DEPLOYMENT_NOT_ALLOWED_REASON_TRAINING:0 "無法§R部署§!訓練進度未達 $VALUE|1H%$ 的部隊（目前為$CURRENT|1R%$）"
 DEPLOYMENT_NOT_ALLOWED_REASON_SPECIAL_FORCES:0 "無法§R部署§!超出額度上限的特種部隊"
 DEPLOYMENT_HOW_TO_DESC:0 "在列表中選擇準備好部署的單位，並且在地圖上的提示省份上§G點擊左鍵§!，即可部署。\n§g在部署時沒有裝備齊全的單位將通過增援獲得剩下的裝備。\n請注意，提前部署的單位將會無法得到充分的訓練。§!"
 OPERATIONS_DESC:1 "§Y行動§!\n§T設置間諜行動獲得裝備的優先級§!"
 OPERATIONS_EMPTY:0 "§G目前沒有行動命令§!"
 REINFORCEMENT:0 "增援與補充"
 REINFORCEMENT_DESC:1 "§Y增援§!\n§T調整需要補充裝備的現役部隊獲得裝備的優先程度，其次則是需要升級與正在訓練的部隊§!。"
 REINFORCEMENT_EMPTY:0 "§G目前沒有單位需要補充裝備。§!"
 UPGRADES:0 "升級與替換"
 UPGRADES_DESC:1 "§Y升級§!\n§T調整需要升級裝備的現役部隊獲得裝備的優先程度，其次則是需要補給與正在訓練的部隊§!。"
 UPGRADES_EMPTY:0 "§G目前沒有單位需要升級裝備§!"
 group_infantry_title:0 "步兵"
 group_mobile_title:0 "機動"
 group_armor_title:0 "裝甲"
 group_support_title:1 "支援"
 NEW_GROUP_ADDITIONAL_COST:0 "新增花費：£army_experience£$VALUE|H0$"
 GARRISONS:0 "衛戍部隊"
 GARRISONS_DESC:1 "§Y衛戍§!\n§T設置衛戍部隊獲得裝備的優先級§!"
 GARRISONS_EMPTY:0 "§G目前沒有衛戍命令§!"
 TIMED_ACTIVITY_TITLE:0 "針對$COUNTRY$的$NAME$"
 TIMED_ACTIVITY_ALERT_TITLE:0 "針對$COUNTRY|H$的$NAME|H$"
 TIMED_ACTIVITY_ENTRY_DESC:0 "§T提高生產外交活動所需裝備的優先級§!。"
 TIMED_ACTIVITY_ENTRY_COMPLETE_DESC:0 "§G所需裝備已收集齊全§!。"
 LAND_DEPLOYMENT:0 "§T陸軍部署§!"
 AIR_DEPLOYMENT:0 "§T空軍部署§!"
 NAVAL_DEPLOYMENT:0 "§T海軍部署§!"
 DIVISION_DESIGNER_RENAME:0 "重新命名"
 DIVISION_DESIGNER_UPDATE:0 "升級"
 DEPLOY:0 "部署"
 EDIT:0 "編輯"
 VIEW:0 "檢視"
 COPY:0 "複製"
 DIVISION_EQUIPMENT:1 "裝備"
 NEW_EQUIPMENT_ALLOWED:0 "使用新式裝備"
 DO_NOT_CONTAINS_TEMPLATE:0 "§R此編制不存在，因此無法刪除§!"
 HAS_ARMIES_WITH_TEMPLATE:0 "§R尚有 $AMOUNT|H$ 支應用此編制的單位，因此無法刪除§!"
 HAS_ARMIES_WITH_OLD_TEMPLATE:0 "§R尚有 $AMOUNT|H$ 支應用此編制的單位正在進行改組，因此無法删除。請待改組作業完成。§!"
 HAS_DEPLOYMENT_CONVEYORS_WITH_TEMPLATE:0 "尚有 $AMOUNT|H$ 支未部署的單位應用此編制，因此無法§R删除§!。"
 HAS_GARRISON_WITH_TEMPLATE:0 "§R無法刪除這項編制，因為它已被用於佔領區的衛戍編制§!"
 DEPLOYMENT_TEMPLATE_LABEL:0 "部隊編制"
 TEMPLATE_PRIO_0:0 "後備軍"
 TEMPLATE_PRIO_0_DESC:0 "該層級的單位將以最低優先權獲得升級與增援。適用於防衛部隊。"
 TEMPLATE_PRIO_1:0 "常備軍"
 TEMPLATE_PRIO_1_DESC:0 "該層級的單位將以一般優先權獲得升級與增援。適用於前線部隊。"
 TEMPLATE_PRIO_2:0 "近衛軍"
 TEMPLATE_PRIO_2_DESC:0 "該層級的單位將以最高優先權獲得升級與增援。適用於精銳部隊，使其保持最高水準的戰力。"
 DEPLOYMENT_LEND_LEASE_COUNTRY:0 "租借法案：$COUNTRY$"
 ADD_CONVEYOR_LINE_BUTTON_LABEL:0 "添加單位"
 ADD_CONVEYOR_LINE_BUTTON_DESC:0 "添加一條與其他單位並列的「$CONVEYOR|H$」。\n\n按住「§GShift§!」同時§G點擊左鍵§!，即可一次添加五條「$CONVEYOR|H$」至部署序列中。"
 CONVEYOR_GENERIC_NAME_EDIT_DESC:0 "在此編輯單位的通用名稱。"
 CONVEYOR_TEMPLATE_ICON_DESC:0 "本次部署的單位應用的是$TEMPLATE|H$編制。"
 CANCEL_CONVEYOR_TOOLTIP:0 "§R撤銷§!所有未部署的單位。"
 DEPLOY_CONVEYOR_TOOLTIP:0 "§G點擊左鍵§!，即可部署所有單位。"
 DEPLOY_CONVEYOR_DISABLED_TOOLTIP:0 "§R目前無單位可供部署§!。"
 CONVEYOR_CANCEL_TITLE:0 "§R取消§!生產"
 CONVEYOR_CANCEL_DESC:0 "您確定要§R撤銷§!所有未部署的單位嗎？"
 CONVEYOR_LINE_CANCEL_DESC:0 "§R撤銷§!這個未部署的單位。"
 CONVEYOR_LINE_CANCEL_ACCEPT_TITLE:0 "§R撤銷§!部署序列"
 CONVEYOR_LINE_CANCEL_ACCEPT_SINGLE_DESC:0 "您確定要§R撤銷§!所有未部署的單位嗎？\n（已部署單位也會同時被§R移除§!）"
 CONVEYOR_LINE_CANCEL_ACCEPT_DESC:0 "您確定要§R撤銷§!這個未部署的單位嗎？"
 CONVEYOR_GROUP_ASSIGN_DESC:0 "§G點擊左鍵§!，即可分配作戰命令。\n§G點擊右鍵§!，即可重新分配作戰命令。"
 CONVEYOR_GROUP_CAN_NOT_ASSIGN_NO_ORDERS_DESC:0 "要將單位編入軍團，至少需要分配一項戰區的作戰命令。"
 CONVEYOR_GROUP_CAN_NOT_ASSIGN_NO_LOCATION_DESC:0 "要將單位編入軍團，至少需要設定部署地點。"
 CONVEYOR_SET_LOCATION_DESC:0 "§G點擊左鍵§!，即可設置部署地點。\n§G點擊右鍵§!，即可重新設置。"
 CONVEYOR_SET_COLONIAL_LOCATION_DESC:0 "§G點擊左鍵§!，即可設置部署地點。\n§G點擊右鍵§!，即可重新設置。\n§Y殖民地編制僅能部署在殖民地！§!"
 CONVEYOR_SET_LOCATION_NOT_SET:0 "§R尚未設置地點§!"
 CONVEYOR_LINE_PREFIX_NAME_EDIT_DESC:0 "在此編輯單位的前綴。"
 CONVEYOR_LINE_DEPLOY_DESC:0 "§G點擊左鍵§!，即可馬上部署單位。"
 CONVEYOR_SERIES_INCREASE_DESC:0 "增加此序列的部隊數量。\n\n將數值設為「無限」意味著啟用自動訓練的重複循環。"
 CONVEYOR_SERIES_AMOUNT_DESC:0 "此序列剩餘的部隊數量。\n\n將數值設為「無限」意味著啟用自動訓練的重複循環。"
 CONVEYOR_SERIES_DECREASE_DESC:0 "減少此序列的部隊數量。\n\n將數值設為「無限」意味著啟用自動訓練的重複循環。"
 CONVEYOR_LOW_PRIORITY_DESC:0 "最低優先權"
 CONVEYOR_MEDIUM_PRIORITY_DESC:0 "一般優先權"
 CONVEYOR_HIGH_PRIORITY_DESC:0 "最高優先權"
 CONVEYOR_CAN_NOT_TRAIN:0 "§R裝備不足，無法訓練§!"
 CONVEYOR_CAN_NOT_MANPOWER_TRAIN:0 "§R兵員不足，無法訓練§!"
 CONVEYOR_CAN_NOT_TRAIN_COUNT:1 "§R有 $DIVS$ 支部隊的兵員或裝備不足，無法訓練§!"
 CONVEYOR_COLLAPSE_DESC:0 "§G點擊左鍵§!，即可摺疊"
 CONVEYOR_EXPAND_DESC:0 "§G點擊左鍵§!，即可展開"
 CONVEYOR_MOVE_UP:0 "§G點擊左鍵§!，即可向上移動\n按住「§GShift§!」同時§G點擊左鍵§!，即可移至頂部"
 CONVEYOR_MOVE_DOWN:0 "§G點擊左鍵§!，即可向下移動\n按住「§GShift§!」同時§G點擊左鍵§!，即可移至底部"
 DEPLOYMENT_LOW_PRIORITY_DESC:0 "最低優先權"
 DEPLOYMENT_MEDIUM_PRIORITY_DESC:0 "一般優先權"
 DEPLOYMENT_HIGH_PRIORITY_DESC:0 "最高優先權"
 CONVEYOR_HAS_BAD_LOCATION:0 "目標位置目前§R無法§!部署單位。"
 CONVEYOR_TRAINING_NOT_FINISHED:0 "該序列的訓練尚未完成。"
 CONVEYOR_SERIES_CURRENT_AMOUNT_DESC:0 "該序列目前的編號。"
 CONVEYOR_LINE_SERIES_BASE:0 "$CURRENT$/$TARGET$"
 DEPLOYMENT_LINE_NAME_OVERRIDE_CANCEL:0 "§H清除自定義名稱§!\n將嘗試恢復原來分配的名稱，除非已被佔用。"
 DEPLOYMENT_LINE_CHOOSE_OTHER_NAME:0 "§H選擇另一個歷史名稱。§!\n§G點擊左鍵§!，即可打開可用的名稱列表。或是通過編輯修改。"
 DEPLOYMENT_LINE_EDIT_NAME:0 "§G點擊左鍵§!，即可使用自定義名稱。"
 DEPLOYMENT_LINE_OUT_OF_NAMES:0 "§g尚無歷史名稱可用§!"
 MISSING_SPECIAL_FORCES_CAP:0 "§R特種部隊的額度已達上限§!"
 TRAINING_HALTED:0 "訓練已中止\n"
 CANNOT_DELETE_SPECIAL_TEMPLATES:0 "無法刪除特殊編制。"
 DEPLOYMENT_CANNOT_TRAIN_SPECIAL_UNITS:1 "無法訓練更多特種部隊。"
 DEPLOYMENT_EXILE_WITH_NO_CAPITAL:0 "除非奪回§H首都§!，否則§H流亡政府§!無法編組新部隊。"
 CANT_CHANGE_DUE_TO_SPECIAL_FORCES_CAP:0 "無法更改編制，因為特種部隊的額度已達上限。"
 NO_SPECIAL_FORCES:0 "此編制不含特種部隊"
 SPECIAL_FORCES_IN_TEMPLATE:1 "此編制包含了$NUM|Y$個特種部隊營"
 SPECIAL_FORCES_CAP_DESC:0 "已部署 $USED|Y$ 支特種部隊，另有 $IN_TRAINING|Y$ 支正在訓練中的特種部隊。特種部隊的上限為 $CAP|Y$ 支。"
 DEPLOYMENT_MAX_DEPLOYABLE_DIVISION_FOR_TEMPLATE:0 "將會空出 $TRAINABLE|Y$ 支特種部隊的額度。"
 SHOW_DECOMMISSIONED_TEMPLATES:0 "顯示§H已除役編制§!"
 DECOMMISSION_TEMPLATE_TOGGLE_ON:0 "除役"
 DECOMMISSION_TEMPLATE_TOGGLE_ON_DESC:0 "§G點擊左鍵§!以將此編制除役，標記其為退役編制。"
 DECOMMISSION_TEMPLATE_TOGGLE_OFF:0 "現役"
 DECOMMISSION_TEMPLATE_TOGGLE_OFF_DESC:0 "§G點擊左鍵§!將此編制恢復現役，標記其為服役編制。"
 DEPLOYMENT_LINES_HIT_THE_DIVISION_CAP:0 "§R此編制的額度已達上限§!\n"
 DEPLOYMENT_NOT_ALLOWED_REASON_EXCEED_DIVISION_CAP:0 "無法§R部署§!超出編制額度上限的部隊"
 EXCEEDING_DIVISION_CAP:0 "§R此編制的額度已超過上限§!"
 CANT_CHANGE_DUE_TO_DIVISION_CAP:0 "無法更改編制，因為部隊額度已達上限。"
 SPECIAL_FORCES_CAP_LIMIT_DESC:0 "此編制上限等同於特種部隊的數量上限，因為這是最低的限制。"
 DIVISION_CAP_OF_TEMPLATE:0 "此編制的數量上限為$NUM|Y$。"
 DIVISION_CAP_USAGE_DESC:0 "$NAME|Y$目前已經部署了$USED|Y$個師，正在訓練$IN_TRAINING|Y$個師，上限為$CAP|Y$個師。"
 DIVISION_CAP_LIMIT_DESC:0 "此師使用該編制的上限，因為這是最低的限制。"